# Generated by Django 3.2.8 on 2021-11-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=128)),
                ('nevisande', models.CharField(max_length=128)),
                ('salechap', models.CharField(max_length=128)),
                ('tedade_safahat', models.CharField(max_length=128)),
                ('tozih', models.TextField()),
            ],
        ),
    ]
